CREATE SEQUENCE SEQ_BOARD;

CREATE TABLE TBL_BOARD(
   BOARD_ID NUMBER CONSTRAINT PK_BOARD PRIMARY KEY,
   BOARD_TITLE VARCHAR2(500) NOT NULL,
   BOARD_CONTENT VARCHAR2(1000) NOT NULL,
   BOARD_REGISTER_DATE DATE,
   BOARD_UPDATE_DATE DATE,
   USER_ID NUMBER NOT NULL,
   CONSTRAINT FK_BOARD_USER FOREIGN KEY(USER_ID) REFERENCES TBL_USER(USER_ID)
   ON DELETE CASCADE
);

SELECT * FROM TBL_BOARD;

SELECT REPLY_ID, REPLY_CONTENT, REPLY_REGISTER_DATE, REPLY_UPDATE_DATE, USER_ID, BOARD_ID, REPLY_GROUP, REPLY_DEPTH
FROM TBL_REPLY R JOIN TBL_USER U
ON R.USER_ID  = U.USER_ID AND REPLY_ID = ?;
